import * as Phaser from 'phaser'; import { PALETTE } from '../../config/palette'; import { mixColor } from '../../utils/color'; import type { DayPhase } from '../time/GameTimeService'; import type { DistrictDefinition } from '../../world/types';
export class StreetSlice {
  public readonly worldWidth:number; public readonly worldHeight:number; public readonly walkTop:number; public readonly walkBottom:number; public readonly interactables:DistrictDefinition['interactables']; private readonly scene:Phaser.Scene; private readonly root:Phaser.GameObjects.Container; private readonly animated:Phaser.GameObjects.Ellipse[]=[]; private readonly ambient:Phaser.GameObjects.Rectangle; private ambientAlpha=0; private targetAmbient=0;
  public constructor(scene:Phaser.Scene, private readonly district:DistrictDefinition){this.scene=scene;this.worldWidth=district.width;this.worldHeight=district.height;this.walkTop=0;this.walkBottom=district.height;this.interactables=district.interactables;this.root=scene.add.container(0,0).setDepth(-100);this.draw();this.ambient=scene.add.rectangle(district.width/2,district.height/2,district.width,district.height,0x07101b,0);this.ambient.setDepth(1000);this.root.add(this.ambient);}
  public update():void{for(const light of this.animated)light.setAlpha(.12+Math.sin(this.scene.time.now*.002+light.x)*.035);this.ambientAlpha+=(this.targetAmbient-this.ambientAlpha)*.025;this.ambient.setAlpha(this.ambientAlpha);}
  public setPhase(phase:DayPhase):void{this.targetAmbient=phase==='morning'?.05:phase==='day'?0:phase==='evening'?.14:phase==='night'?.28:.4;}
  public destroy():void{this.root.destroy(true);}
  private draw():void{const g=this.scene.add.graphics();for(let i=0;i<24;i+=1){const t=i/23;g.fillStyle(mixColor(0x25313a,PALETTE.skyHorizon,t),1);g.fillRect(0,t*this.district.height,this.district.width,this.district.height/23+2);}for(const road of this.district.roads){g.fillStyle(0x25282d,1);g.fillRect(road.bounds.x,road.bounds.y,road.bounds.width,road.bounds.height);g.lineStyle(2,0x77705f,.3);if(road.direction==='horizontal'){for(let x=road.bounds.x+30;x<road.bounds.x+road.bounds.width;x+=90)g.strokeLineShape(new Phaser.Geom.Line(x,road.bounds.y+road.bounds.height/2,x+45,road.bounds.y+road.bounds.height/2));}else{for(let y=road.bounds.y+30;y<road.bounds.y+road.bounds.height;y+=90)g.strokeLineShape(new Phaser.Geom.Line(road.bounds.x+road.bounds.width/2,y,road.bounds.x+road.bounds.width/2,y+45));}}
    g.fillStyle(0x34363b,1);g.fillRect(0,0,this.district.width,this.district.height);for(const road of this.district.roads){g.fillStyle(0x24272c,1);g.fillRect(road.bounds.x,road.bounds.y,road.bounds.width,road.bounds.height);g.lineStyle(2,0x8b846f,.32);if(road.direction==='horizontal'){for(let x=road.bounds.x+30;x<road.bounds.x+road.bounds.width;x+=100)g.strokeLineShape(new Phaser.Geom.Line(x,road.bounds.y+road.bounds.height/2,x+50,road.bounds.y+road.bounds.height/2));}else{for(let y=road.bounds.y+30;y<road.bounds.y+road.bounds.height;y+=100)g.strokeLineShape(new Phaser.Geom.Line(road.bounds.x+road.bounds.width/2,y,road.bounds.x+road.bounds.width/2,y+50));}}
    this.root.add(g);this.drawBuildings();this.drawProps();}
  private drawBuildings():void{for(const building of this.district.buildings){const group=this.scene.add.container(building.x,building.y);const art=this.scene.add.graphics();art.fillStyle(0x12151b,1);art.fillRect(0,70,building.width,building.height);art.fillStyle(0x272d35,1);art.fillTriangle(0,70,building.width,70,building.width*.84,0);art.fillStyle(0x3c4149,1);art.fillRect(0,70,building.width,14);art.fillStyle(0xe2a648,.38);for(let x=35;x<building.width-25;x+=105){for(let y=120;y<building.height-30;y+=110){art.fillRect(x,y,38,24);}}art.fillStyle(0x343941,1);art.fillRect(building.width*.42,building.height-70,72,70);art.fillStyle(0x9fb4c7,.42);art.fillRect(building.width*.46,building.height-62,28,48);group.add(art);if(building.label)group.add(this.scene.add.text(building.width/2,building.height-104,building.label,{fontFamily:'system-ui',fontSize:'18px',color:'#d1ccc1'}).setOrigin(.5));group.setDepth(building.y+building.height);this.root.add(group);}}
  private drawProps():void{for(const prop of this.district.props){const group=this.scene.add.container(prop.x,prop.y);const art=this.scene.add.graphics();if(prop.kind==='tree'){art.fillStyle(0x201713,1);art.fillRect(-8,-90,16,90);art.fillStyle(0x263b35,1);art.fillCircle(0,-112,48);art.fillStyle(0x3d5143,.8);art.fillCircle(-20,-126,26);}else if(prop.kind==='lamp'){art.fillStyle(0x0a0b0f,1);art.fillRect(-4,-120,8,120);art.fillRect(-4,-120,38,6);const light=this.scene.add.ellipse(38,-111,100,100,PALETTE.lampGlow,.12);this.animated.push(light);group.add(light);}else if(prop.kind==='parked-car'){art.fillStyle(0x0b0c0f,.55);art.fillEllipse(0,15,120,24);art.fillStyle(0x4d5860,1);art.fillRoundedRect(-55,-35,110,55,9);art.fillStyle(0x1d2932,1);art.fillRect(-28,-55,56,24);art.fillStyle(0x101216,1);art.fillCircle(-38,18,10);art.fillCircle(38,18,10);}else if(prop.kind==='sign'){art.fillStyle(0x171a20,1);art.fillRect(-4,-80,8,80);art.fillStyle(PALETTE.accent,1);art.fillRect(-35,-98,70,32);}else{art.fillStyle(0x252a31,1);art.fillRect(-22,-26,44,52);}group.add(art);group.setDepth(prop.y);this.root.add(group);}}
}
