import * as Phaser from 'phaser';
import type { AppearancePreset, ClothingPreset } from '../../data/game/player';
const SKIN:Record<AppearancePreset,number>={'night-owl':0xb67e63,'red-cap':0xd6a07c,'quiet-one':0x8f604d,'street-poet':0xc28f70,'winter-kid':0xe0ad89,'lucky-scarf':0xa97058};
const HAIR:Record<AppearancePreset,number>={'night-owl':0x171922,'red-cap':0x6e3628,'quiet-one':0x2a2223,'street-poet':0xd6b18a,'winter-kid':0xaeb5bd,'lucky-scarf':0x20191a};
const COAT:Record<ClothingPreset,number>={'old-jacket':0x4a4d50,hoodie:0x5d4650,'worn-sweatshirt':0x394a4b,'long-coat':0x252c39};
export class Player extends Phaser.GameObjects.Container { private readonly art:Phaser.GameObjects.Graphics; private readonly shadow:Phaser.GameObjects.Ellipse; private moving=false; private sitting=false; private bob=0; private facing:'N'|'E'|'S'|'W'='S'; private readonly appearance:AppearancePreset; private readonly clothing:ClothingPreset;
 public constructor(scene:Phaser.Scene,appearance:AppearancePreset,clothing:ClothingPreset){super(scene,0,0);this.appearance=appearance;this.clothing=clothing;this.art=scene.add.graphics();this.shadow=scene.add.ellipse(0,18,40,12,0x05060a,.45);this.add([this.shadow,this.art]);this.draw();this.setDepth(600);scene.add.existing(this);}
 public setMoving(value:boolean):void{this.moving=value&&!this.sitting;} public setSitting(value:boolean):void{this.sitting=value;this.moving=false;this.draw();} public setFacing(x:number,y:number):void{if(Math.abs(x)>Math.abs(y))this.facing=x<0?'W':'E';else if(Math.abs(y)>0)this.facing=y<0?'N':'S';}
 public updateVisual(delta:number):void{this.bob+=delta*(this.moving?.018:.004);this.art.y=this.sitting?0:(this.moving?Math.sin(this.bob)*2:Math.sin(this.bob)*.5);this.setDepth(Math.round(this.y)+600);}
 public getPosition():{x:number;y:number}{return{x:this.x,y:this.y};}
 private draw():void{const skin=SKIN[this.appearance],hair=HAIR[this.appearance],coat=COAT[this.clothing];this.art.clear();if(this.sitting){this.art.fillStyle(coat,1);this.art.fillRoundedRect(-22,-46,44,30,7);this.art.fillStyle(skin,1);this.art.fillCircle(0,-57,13);this.art.fillStyle(hair,1);this.art.fillEllipse(0,-67,28,11);this.art.fillStyle(0x15171d,1);this.art.fillRect(-22,-14,19,6);this.art.fillRect(3,-14,19,6);return;}this.art.fillStyle(coat,1);this.art.fillRoundedRect(-19,-62,38,42,8);this.art.fillStyle(coat,1);this.art.fillRoundedRect(-29,-55,10,30,4);this.art.fillRoundedRect(19,-55,10,30,4);this.art.fillStyle(0x14151b,1);this.art.fillRoundedRect(-16,-20,12,24,4);this.art.fillRoundedRect(4,-20,12,24,4);this.art.fillStyle(0x0b0c0f,1);this.art.fillRect(-17,2,14,5);this.art.fillRect(3,2,14,5);this.art.fillStyle(skin,1);this.art.fillCircle(0,-78,16);this.art.fillStyle(hair,1);this.art.fillEllipse(0,-91,31,13);this.art.fillStyle(0x15171d,1);this.art.fillCircle(this.facing==='W'?5:-5,-78,2);this.art.fillCircle(this.facing==='E'?-5:5,-78,2);if(this.appearance==='red-cap'){this.art.fillStyle(0xb5483f,1);this.art.fillEllipse(0,-96,33,9);}if(this.appearance==='lucky-scarf'){this.art.fillStyle(0xc98f36,1);this.art.fillRect(-17,-53,34,6);}}
}
